# Grafana admin secret
# Variables: ENVIRONMENT, NAMESPACE, GF_SECURITY_ADMIN_*_B64
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret-$ENVIRONMENT
  namespace: $NAMESPACE
  labels:
    app: grafana
    environment: $ENVIRONMENT
type: Opaque
data:
  GF_SECURITY_ADMIN_USER: $GF_SECURITY_ADMIN_USER_B64
  GF_SECURITY_ADMIN_PASSWORD: $GF_SECURITY_ADMIN_PASSWORD_B64
