# Grafana Postgres datasource secret
# Variables: ENVIRONMENT, NAMESPACE, PG_*_B64
apiVersion: v1
kind: Secret
metadata:
  name: grafana-postgres-secret-dev
  namespace: smart-dc-dev
  labels:
    app: grafana
    environment: dev
type: Opaque
data:
  PG_USER: a2RjaGRiMDA1
  PG_PASSWORD: MlRjMkFVeXBkbkZy
  PG_HOST: Yy5rZGNoLXNnLWFpbWwtcG9zdGdyZXNxbC1kZXYtMDIucG9zdGdyZXMuZGF0YWJhc2UuYXp1cmUuY29t
  PG_DATABASE: Y2l0dXM=
  PG_PORT: NTQzMg==
  PG_PROD_USER: a2RjaGRiMDA1
  PG_PROD_PASSWORD: MlRjMkFVeXBkbkZy
  PG_PROD_HOST: a2RjaC1zZy1haW1sLXBvc3RncmVzcWwtMDEtYy5wb3N0Z3Jlcy5kYXRhYmFzZS5henVyZS5jb20=
  PG_PROD_DATABASE: Y2l0dXM=
  PG_PROD_PORT: NTQzMg==
